workflows:
  native-android:
    name: Native Android
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.nb.test"
      android_signing:
        - nitesh
    scripts:
      - name: Set Android SDK location
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
    artifacts:
      - app/build/outputs/**/*.aab
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - nitesh@deinfra.io
        notify:
          success: true
          failure: true